### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by summerstyle** [summerstyle/app.js#1]
- [x] create layers object
- [x] test layers
- [ ] create events module
- [ ] support keys
- [ ] change class names. make it unique on the page
- [ ] add style for all usually needed elements (form and text)
- [ ] work with windows - like {position: fixed}
